({
    saveInlineRetention : function(cmp, event) {
        var params = event.getParam('arguments');        
        var obj = params.parentNewRequest;       
        obj.ContractorNameKanaSei__c = cmp.get("v.innerCmpNewRequest").ContractorNameKanaSei__c;
		obj.ContractorNameKanaMei__c = cmp.get("v.innerCmpNewRequest").ContractorNameKanaMei__c;
		obj.ContinuationProposal__c = cmp.get("v.innerCmpNewRequest").ContinuationProposal__c;
		obj.ReasonForProposal__c = cmp.get("v.innerCmpNewRequest").ReasonForProposal__c; 		
		obj.ProposalContent__c = cmp.get("v.innerCmpNewRequest").ProposalContent__c;
		obj.CancellationReasonFree__c = cmp.get("v.innerCmpNewRequest").CancellationReasonFree__c;
		obj.ContentsOfGuidance__c = cmp.get("v.innerCmpNewRequest").ContentsOfGuidance__c;
		obj.FinalResultReason__c = cmp.get("v.innerCmpNewRequest").FinalResultReason__c;
		obj.Comment2__c = cmp.get("v.innerCmpNewRequest").Comment2__c;
		obj.Ret1_PolicyNumber__c = cmp.get("v.innerCmpNewRequest").Ret1_PolicyNumber__c;
		obj.Ret1_FirstOffer__c = cmp.get("v.innerCmpNewRequest").Ret1_FirstOffer__c;
		obj.Ret1_InsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret1_InsuranceFee__c;
		obj.Ret1_FinalResults__c = cmp.get("v.innerCmpNewRequest").Ret1_FinalResults__c;
		obj.Ret1_ChangedInsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret1_ChangedInsuranceFee__c;
		obj.Ret1_CancellationRequestEndOfMonth__c = cmp.get("v.innerCmpNewRequest").Ret1_CancellationRequestEndOfMonth__c;
		obj.Ret1_RejectReceiving__c = cmp.get("v.innerCmpNewRequest").Ret1_RejectReceiving__c;
		obj.Ret1_CancellationRequestConditional__c = cmp.get("v.innerCmpNewRequest").Ret1_CancellationRequestConditional__c;
		obj.Ret1_Cancel__c = cmp.get("v.innerCmpNewRequest").Ret1_Cancel__c;
		obj.Ret2_PolicyNumber__c = cmp.get("v.innerCmpNewRequest").Ret2_PolicyNumber__c;
		obj.Ret2_FirstOffer__c = cmp.get("v.innerCmpNewRequest").Ret2_FirstOffer__c;
		obj.Ret2_InsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret2_InsuranceFee__c;
		obj.Ret2_FinalResults__c = cmp.get("v.innerCmpNewRequest").Ret2_FinalResults__c;
		obj.Ret2_ChangedInsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret2_ChangedInsuranceFee__c;
		obj.Ret2_CancellationRequestEndOfMonth__c = cmp.get("v.innerCmpNewRequest").Ret2_CancellationRequestEndOfMonth__c;
		obj.Ret2_RejectReceiving__c = cmp.get("v.innerCmpNewRequest").Ret2_RejectReceiving__c;
		obj.Ret2_CancellationRequestConditional__c = cmp.get("v.innerCmpNewRequest").Ret2_CancellationRequestConditional__c;
		obj.Ret2_Cancel__c = cmp.get("v.innerCmpNewRequest").Ret2_Cancel__c;
		obj.Ret3_PolicyNumber__c = cmp.get("v.innerCmpNewRequest").Ret3_PolicyNumber__c;
		obj.Ret3_FirstOffer__c = cmp.get("v.innerCmpNewRequest").Ret3_FirstOffer__c;
		obj.Ret3_InsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret3_InsuranceFee__c;
		obj.Ret3_FinalResults__c = cmp.get("v.innerCmpNewRequest").Ret3_FinalResults__c;
		obj.Ret3_ChangedInsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret3_ChangedInsuranceFee__c;
		obj.Ret3_CancellationRequestEndOfMonth__c = cmp.get("v.innerCmpNewRequest").Ret3_CancellationRequestEndOfMonth__c;
		obj.Ret3_RejectReceiving__c = cmp.get("v.innerCmpNewRequest").Ret3_RejectReceiving__c;
		obj.Ret3_CancellationRequestConditional__c = cmp.get("v.innerCmpNewRequest").Ret3_CancellationRequestConditional__c;
		obj.Ret3_Cancel__c = cmp.get("v.innerCmpNewRequest").Ret3_Cancel__c;
		obj.Ret4_PolicyNumber__c = cmp.get("v.innerCmpNewRequest").Ret4_PolicyNumber__c;
		obj.Ret4_FirstOffer__c = cmp.get("v.innerCmpNewRequest").Ret4_FirstOffer__c;
		obj.Ret4_InsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret4_InsuranceFee__c;
		obj.Ret4_FinalResults__c = cmp.get("v.innerCmpNewRequest").Ret4_FinalResults__c;
		obj.Ret4_ChangedInsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret4_ChangedInsuranceFee__c;
		obj.Ret4_CancellationRequestEndOfMonth__c = cmp.get("v.innerCmpNewRequest").Ret4_CancellationRequestEndOfMonth__c;
		obj.Ret4_RejectReceiving__c = cmp.get("v.innerCmpNewRequest").Ret4_RejectReceiving__c;
		obj.Ret4_CancellationRequestConditional__c = cmp.get("v.innerCmpNewRequest").Ret4_CancellationRequestConditional__c;
		obj.Ret4_Cancel__c = cmp.get("v.innerCmpNewRequest").Ret4_Cancel__c;
		obj.Ret5_PolicyNumber__c = cmp.get("v.innerCmpNewRequest").Ret5_PolicyNumber__c;
		obj.Ret5_FirstOffer__c = cmp.get("v.innerCmpNewRequest").Ret5_FirstOffer__c;
		obj.Ret5_InsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret5_InsuranceFee__c;
		obj.Ret5_FinalResults__c = cmp.get("v.innerCmpNewRequest").Ret5_FinalResults__c;
		obj.Ret5_ChangedInsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret5_ChangedInsuranceFee__c;
		obj.Ret5_CancellationRequestEndOfMonth__c = cmp.get("v.innerCmpNewRequest").Ret5_CancellationRequestEndOfMonth__c;
		obj.Ret5_RejectReceiving__c = cmp.get("v.innerCmpNewRequest").Ret5_RejectReceiving__c;
		obj.Ret5_CancellationRequestConditional__c = cmp.get("v.innerCmpNewRequest").Ret5_CancellationRequestConditional__c;
		obj.Ret5_Cancel__c = cmp.get("v.innerCmpNewRequest").Ret5_Cancel__c;
		obj.Ret6_PolicyNumber__c = cmp.get("v.innerCmpNewRequest").Ret6_PolicyNumber__c;
		obj.Ret6_FirstOffer__c = cmp.get("v.innerCmpNewRequest").Ret6_FirstOffer__c;
		obj.Ret6_InsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret6_InsuranceFee__c;
		obj.Ret6_FinalResults__c = cmp.get("v.innerCmpNewRequest").Ret6_FinalResults__c;
		obj.Ret6_ChangedInsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret6_ChangedInsuranceFee__c;
		obj.Ret6_CancellationRequestEndOfMonth__c = cmp.get("v.innerCmpNewRequest").Ret6_CancellationRequestEndOfMonth__c;
		obj.Ret6_RejectReceiving__c = cmp.get("v.innerCmpNewRequest").Ret6_RejectReceiving__c;
		obj.Ret6_CancellationRequestConditional__c = cmp.get("v.innerCmpNewRequest").Ret6_CancellationRequestConditional__c;
		obj.Ret6_Cancel__c = cmp.get("v.innerCmpNewRequest").Ret6_Cancel__c;
		obj.Ret7_PolicyNumber__c = cmp.get("v.innerCmpNewRequest").Ret7_PolicyNumber__c;
		obj.Ret7_FirstOffer__c = cmp.get("v.innerCmpNewRequest").Ret7_FirstOffer__c;
		obj.Ret7_InsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret7_InsuranceFee__c;
		obj.Ret7_FinalResults__c = cmp.get("v.innerCmpNewRequest").Ret7_FinalResults__c;
		obj.Ret7_ChangedInsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret7_ChangedInsuranceFee__c;
		obj.Ret7_CancellationRequestEndOfMonth__c = cmp.get("v.innerCmpNewRequest").Ret7_CancellationRequestEndOfMonth__c; 		
		obj.Ret7_RejectReceiving__c = cmp.get("v.innerCmpNewRequest").Ret7_RejectReceiving__c;
		obj.Ret7_CancellationRequestConditional__c = cmp.get("v.innerCmpNewRequest").Ret7_CancellationRequestConditional__c;
		obj.Ret7_Cancel__c = cmp.get("v.innerCmpNewRequest").Ret7_Cancel__c;
		obj.Ret8_PolicyNumber__c = cmp.get("v.innerCmpNewRequest").Ret8_PolicyNumber__c;
		obj.Ret8_FirstOffer__c = cmp.get("v.innerCmpNewRequest").Ret8_FirstOffer__c;
		obj.Ret8_InsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret8_InsuranceFee__c;
		obj.Ret8_FinalResults__c = cmp.get("v.innerCmpNewRequest").Ret8_FinalResults__c;
		obj.Ret8_ChangedInsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret8_ChangedInsuranceFee__c;
		obj.Ret8_CancellationRequestEndOfMonth__c = cmp.get("v.innerCmpNewRequest").Ret8_CancellationRequestEndOfMonth__c;
		obj.Ret8_RejectReceiving__c = cmp.get("v.innerCmpNewRequest").Ret8_RejectReceiving__c;
		obj.Ret8_CancellationRequestConditional__c = cmp.get("v.innerCmpNewRequest").Ret8_CancellationRequestConditional__c;
		obj.Ret8_Cancel__c = cmp.get("v.innerCmpNewRequest").Ret8_Cancel__c;
		obj.Ret9_PolicyNumber__c = cmp.get("v.innerCmpNewRequest").Ret9_PolicyNumber__c;
		obj.Ret9_FirstOffer__c = cmp.get("v.innerCmpNewRequest").Ret9_FirstOffer__c;
		obj.Ret9_InsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret9_InsuranceFee__c;
		obj.Ret9_FinalResults__c = cmp.get("v.innerCmpNewRequest").Ret9_FinalResults__c;
		obj.Ret9_ChangedInsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret9_ChangedInsuranceFee__c;
		obj.Ret9_CancellationRequestEndOfMonth__c = cmp.get("v.innerCmpNewRequest").Ret9_CancellationRequestEndOfMonth__c;
		obj.Ret9_RejectReceiving__c = cmp.get("v.innerCmpNewRequest").Ret9_RejectReceiving__c;
		obj.Ret9_CancellationRequestConditional__c = cmp.get("v.innerCmpNewRequest").Ret9_CancellationRequestConditional__c;
		obj.Ret9_Cancel__c = cmp.get("v.innerCmpNewRequest").Ret9_Cancel__c;
		obj.Ret10_PolicyNumber__c = cmp.get("v.innerCmpNewRequest").Ret10_PolicyNumber__c;
		obj.Ret10_FirstOffer__c = cmp.get("v.innerCmpNewRequest").Ret10_FirstOffer__c;
		obj.Ret10_InsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret10_InsuranceFee__c;
		obj.Ret10_FinalResults__c = cmp.get("v.innerCmpNewRequest").Ret10_FinalResults__c;
		obj.Ret10_ChangedInsuranceFee__c = cmp.get("v.innerCmpNewRequest").Ret10_ChangedInsuranceFee__c;
		obj.Ret10_CancellationRequestEndOfMonth__c = cmp.get("v.innerCmpNewRequest").Ret10_CancellationRequestEndOfMonth__c;
		obj.Ret10_RejectReceiving__c = cmp.get("v.innerCmpNewRequest").Ret10_RejectReceiving__c;
		obj.Ret10_CancellationRequestConditional__c = cmp.get("v.innerCmpNewRequest").Ret10_CancellationRequestConditional__c;
		obj.Ret10_Cancel__c = cmp.get("v.innerCmpNewRequest").Ret10_Cancel__c;
    },    
    init : function(component,event,helper){
		var dependantSubject = component.get('v.dependantSubject');
		helper.getcontinuationProposalPicklist(component, event,dependantSubject);
		helper.getreasonForProposalPicklist(component, event,dependantSubject);
		helper.getproposalContentPicklist(component, event,dependantSubject);
        helper.getcancellationReasonPicklist(component, event);
		helper.getcontentsOfGuidancePicklist(component, event,dependantSubject);
		helper.getfinalResultReasonPicklist(component, event);
        helper.getret1FirstOfferPicklist(component, event);
		helper.getret1FinalResultsPicklist(component, event);
        helper.getret2FirstOfferPicklist(component, event);
		helper.getret2FinalResultsPicklist(component, event);
		helper.getret3FirstOfferPicklist(component, event);
		helper.getret3FinalResultsPicklist(component, event);
		helper.getret4FirstOfferPicklist(component, event);
		helper.getret4FinalResultsPicklist(component, event);
		helper.getret5FirstOfferPicklist(component, event);
		helper.getret5FinalResultsPicklist(component, event);
		helper.getret6FirstOfferPicklist(component, event);
		helper.getret6FinalResultsPicklist(component, event);
        helper.getret7FirstOfferPicklist(component, event);
		helper.getret7FinalResultsPicklist(component, event);
		helper.getret8FirstOfferPicklist(component, event);
		helper.getret8FinalResultsPicklist(component, event);
		helper.getret9FirstOfferPicklist(component, event);
		helper.getret9FinalResultsPicklist(component, event);
		helper.getret10FirstOfferPicklist(component, event);
		helper.getret10FinalResultsPicklist(component, event);
	},
	handleProposalContentPicklistChange :  function(component,event,helper){
		var selectedValues = event.getParam("value");
	}
	  
})